"""alter table budgets -> removing fields month and year and adding field month_year

Revision ID: 281cbff20147
Revises: 575bbf23f9ec
Create Date: 2022-05-01 10:35:51.086670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281cbff20147'
down_revision = '575bbf23f9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('month_year', sa.Date(), nullable=False))
    op.create_unique_constraint(None, 'budget', ['month_year'])
    op.drop_column('budget', 'month')
    op.drop_column('budget', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('year', sa.VARCHAR(length=45), autoincrement=False, nullable=False))
    op.add_column('budget', sa.Column('month', sa.VARCHAR(length=45), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'budget', type_='unique')
    op.drop_column('budget', 'month_year')
    # ### end Alembic commands ###
