"""alter table user

Revision ID: 575bbf23f9ec
Revises: 5b13b403472b
Create Date: 2022-04-30 02:47:25.669906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575bbf23f9ec'
down_revision = '5b13b403472b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'birthdate',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'birthdate',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
