"""alter table categories removing unique contraint

Revision ID: 8017c2b9a575
Revises: 561e51c43ae9
Create Date: 2022-05-02 10:04:00.157067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8017c2b9a575'
down_revision = '561e51c43ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_description_key', 'category', type_='unique')
    op.drop_constraint('category_name_key', 'category', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('category_name_key', 'category', ['name'])
    op.create_unique_constraint('category_description_key', 'category', ['description'])
    # ### end Alembic commands ###
