"""alter table budgets

Revision ID: ef5154b628dd
Revises: 832c41558b7e
Create Date: 2022-05-01 16:02:48.482275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5154b628dd'
down_revision = '832c41558b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('budget_month_year_key', 'budget', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('budget_month_year_key', 'budget', ['month_year'])
    # ### end Alembic commands ###
